spring:
  application:
    name: phone-number-service

  datasource:
    url: jdbc:h2:mem:phonedb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: "Phone number service for telco"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    display-request-duration: true
    default-model-expand-depth: 1
    default-model-rendering: example
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
